### ISSUE TITLE
静态化部署，供umi build使用

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/codegen#13]
将mock数据解析成静态json，去掉参数，保留正确响应。使得 umi build 之后，不需要部署服务器就可以预览页面，用于项目演示

**Comment by txp1035** [comment]
只是展示不是一眼都在开发环境使用mock数据展示吗，umi build后不是切生产环境了呀。

**Comment by xiaohuoni** [comment]
有很多，演示版本。无服务端

**Comment by txp1035** [comment]
合并到开发计划中了
